"""empty message

Revision ID: 41d8d6c2f129
Revises: 
Create Date: 2024-12-16 22:09:20.552785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d8d6c2f129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lista_de_ordenes', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lista_de_ordenes', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
